service: api-gateway

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

resources:
  Resources:
    ApiGatewayRestApi:
      Type: 'AWS::ApiGateway::RestApi'
      Properties:
        Name: 'SharedApiGateway'

outputs:
  apiGatewayRestApiId:
    value:
      Ref: ApiGatewayRestApi
  apiGatewayRestApiRootResourceId:
    value:
      Fn::GetAtt:
        - ApiGatewayRestApi
        - RootResourceId

plugins:
  - serverless-deployment-bucket